import os, getopt, sys
from termcolor import colored


RFF_BB_VERSION = "20190411.0.0.1"


timeline_log_t = [
    { "name" : "cpu",    "size" : 4, "fmt" : '{:1d}' },
    { "name" : "time",   "size" : 4, "fmt" : '{:10d}' },
    { "name" : "event",  "size" : 4, "enum-map" :
        {
            # Don't touch - it's autogenerated from "event-log.h of 4.15 event logger,
            # commit d1bc3e5c6f501371f917dda024cdffd80c39ec90 (ARC: Low level Event logger)"
            ((0 << 8)|0x01)  : "IRQ_I",
            ((0 << 8)|0x02)  : "IRQ_O",
            ((1 << 8)|0x01)  : "EX_I",
            ((1 << 8)|0x02)  : "EX_O",
            ((2 << 8)|0x01)  : "SYSCALL",
            ((2 << 8)|0x02)  : "TRAP_O",
            ((0 << 8)|0x80)  : "SW_U",
            ((1 << 8)|0x80)  : "SW_K",
            ((4 << 8)|0x01)  : "ITLB",
            ((5 << 8)|0x01)  : "DITLB_Miss_ld",
            ((6 << 8)|0x01)  : "DTLB_Miss_st",
            ((7 << 8)|0x01)  : "ProtV",
            ((7 << 8)|0x80)  : "TLB_slow",
            ((8 << 8)|0x80)  : "TLB_FAST",
            ((3 << 8)|0x80)  : "PREEMPT_I",
            ((6 << 8)|0x80)  : "EXIT",
            ((2 << 8)|0x80)  : "TLB_Flush",
            ((9 << 8)|0x80)  : "IPI_sent",
            ((10 << 8)|0x80) : "ipi_elide",
            ((11 << 8)|0x80) : "dma_ALLOC",
            ((12 << 8)|0x80) : "dma_free",
            ((16 << 8)|0x80) : "cache_wb_inv",
            ((15 << 8)|0x80) : "cache_wb",
            ((14 << 8)|0x80) : "cache_inv",
            ((17 << 8)|0x80) : "MEMSET",
            ((18 << 8)|0x80) : "MEMCPY"
        }
    },
    { "name" : "cause",  "size" : 4, "fmt" : '{:#010x}'  },
    { "name" : "stat32", "size" : 4, "fmt" : '{:#010x}' },
    { "name" : "pc",     "size" : 4, "fmt" : '{:#x}' },
    { "name" : "efa",    "size" : 4, "fmt" : '{:#x}' },
    { "name" : "extra",  "size" : 4, "fmt" : '{:#x}' },
    { "name" : "task",   "size" : 4, "fmt" : '{:#x}' },
    { "name" : "sp",     "size" : 4, "fmt" : '{:#x}' }
]


colorizer_function = colored
split_tab = "; "


def no_color(str, color, attrs=[]):
    return str


def color_header(str):
    return colorizer_function(str, 'white', attrs=['dark'])


def color_value(str):
    return colorizer_function(str, 'green')


def color_idx(str):
    return colorizer_function(str, 'red')


def color_idx_highlight(str):
    return colorizer_function(str, 'blue')


def timeline_log_get_entry_sz(log_t):
    entry_size = 0;

    for var in log_t:
        entry_size += var["size"]

    return entry_size


def entry_var_to_string(var, value):
    enrty_header = color_header(var["name"] + ": ")
    enrty_interpretrd = ""
    if var["size"] == 4:
        enrty_var = int.from_bytes(value, byteorder='little')
        if "fmt" in var:
            enrty_interpretrd += str(var["fmt"].format(enrty_var))
        elif "enum-map" in var:
            if enrty_var in var["enum-map"]:
                enrty_interpretrd += str(var["enum-map"][enrty_var])
            else:
                enrty_interpretrd += "??? (" + hex(enrty_var) + ")"

    return enrty_header + color_value(enrty_interpretrd)


def process_entry(log_t, fi):
    global split_tab
    enrty_interpretrd = ""

    for var in log_t:
        memory_value = fi.read(var["size"])
        if not memory_value:
            return ""
        enrty_interpretrd += entry_var_to_string(var, memory_value)
        enrty_interpretrd += split_tab

    return enrty_interpretrd


def process_entries(log_t, fi, id_start, id_end, id_point):
    entry_id = id_start;

    if id_end < id_start:
        return

    seek_size = timeline_log_get_entry_sz(timeline_log_t) * id_start
    fi.seek(seek_size)

    while (True):
        enrty_interpretrd = process_entry(timeline_log_t, fi)
        if not enrty_interpretrd:
            break

        if entry_id == id_point:
            print(color_idx_highlight('[{:6d}] '.format(entry_id)) + enrty_interpretrd)
        else:
            print(color_idx('[{:6d}] '.format(entry_id)) + enrty_interpretrd)

        if entry_id > id_end:
            break

        entry_id += 1


def usage(exit_code):
    print(sys.argv[0] + " version: " + RFF_BB_VERSION)
    print("usage:")
    print(" " + sys.argv[0] + " --input time-log-mem.txt")
    print(" " + sys.argv[0] + " --start 418000 --end 419920 --curr 419903 --input time-log-mem.txt --tab= --color")
    print(" " + sys.argv[0] + " --curr 100 --input time-log-mem.txt --tab= --color")
    print("options:")
    print(" --input <filename> - file with buffer to open")
    print(" --tab <separator> - use <separator> to split the coloms.\n" \
          "   Default is \"; \"\n" \
          "   If used blank (--tab=) the tabs are used.")
    print(" --start <idx> - don't display buffer values before <idx>")
    print(" --end <idx> - don't display buffer values after <idx>")
    print(" --curr <idx> - highlight current index with color <idx>")
    print(" --align <num> - skip <idx> bytes from the beggining of the file.\n" \
          "   Useful in case bad-captured buffer.")
    print(" --color - force output colorizing")
    sys.exit(exit_code)


def main():
    try:
        opts, args = getopt.getopt(sys.argv[1:], "hs:e:c:i:t:a:l",
            ["help", "start=", "end=", "curr=", "input=", "tab=", "align=", "color"])
    except getopt.GetoptError as err:
        print(err)

    global colorizer_function
    global split_tab

    id_start = 0
    id_end   = 10000000
    id_point = 0
    file_to_parse = "time-log-mem.txt"
    align_cut = 0

    if not sys.stdout.isatty():
        colorizer_function = no_color

    for opt, arg in opts:
        if opt in ('-h', "--help"):  usage(0)
        if opt in ('-l', "--color"):  colorizer_function = colored
        if opt in ('-s', "--start"): id_start  = int(arg, 10)
        if opt in ('-e', "--end"):   id_end    = int(arg, 10)
        if opt in ('-c', "--curr"):  id_point  = int(arg, 10)
        if opt in ('-i', "--input"): file_to_parse = arg
        if opt in ('-t', "--tab"):   split_tab = arg
        if opt in ('-a', "--align"): align_cut  = int(arg, 10)

    if not split_tab:
        split_tab = "\t"

    with open(file_to_parse,'rb') as fi:
        if align_cut:
            fi.seek(align_cut)
        process_entries(timeline_log_t, fi, id_start, id_end, id_point)


if __name__ == "__main__":
    try:
        main()
    except Exception as err:
        print(err)
        sys.exit(2)
